### ISSUE TITLE
Include all stacktrace entries in the list

### ISSUE THREAD

**Issue by fredrikekre** [Klafyvel/nvim-smuggler#27]
Currently frames are filtered out here https://github.com/Klafyvel/nvim-smuggler/blob/83338211f7c438f4c153d9023d9df1388677db15/lua/smuggler/snitch.lua#L20-L22
but I think it would be good to include all entries in the trace so you can easily jump to any frame even if it doesn't belong to buffer that is attached to the smuggler.

**Comment by fredrikekre** [comment]
Yea I saw that too. Perhaps they don't have to be linked? e.g. we can build a quickfix list with all entries and a diagnostic list separately?

**Comment by Klafyvel** [comment]
Yes, that's the way I'm taking in #15. I store the server's responses with the configuration of the buffer and display either the diagnostic or the quickfix list on demand.

**Comment by Klafyvel** [comment]
The quickfix list is now completely separated from the diagnostics, and thus can take you to wherever errors occured!

**Comment by Klafyvel** [comment]
The quickfix list is now completely separated from the diagnostics, and thus can take you to wherever errors occured!
