### ISSUE TITLE
sending a single character to the REPL no longer works

### ISSUE THREAD

**Issue by ArbitRandomUser** [Klafyvel/nvim-smuggler#35]
```
a=1
a
```

send the second line only does not send anything to the repl

**Comment by ArbitRandomUser** [comment]
tested it out on the older version 0.3.0; it seems to have been there before the new release too

**Comment by Klafyvel** [comment]
This is probably a mark positioning error when doing selection by line or by character, most likely in reslime.lua. I'm struggling on the other issue for now and will probably give up for tonight. Perhaps rolling back to an older version is wiser for now.

**Comment by Klafyvel** [comment]
Fixed in REPLSmuggler.jl.
