### ISSUE TITLE
What exactly is evaluated and invalidated 

### ISSUE THREAD

**Issue by ArbitRandomUser** [Klafyvel/nvim-smuggler#39]
```
a=1
b=2
c=3
```

now when i edit them as such ...

I change 3rd line by adding a space after it , it gets invalidated.
but if i change second line after that it does not get invalidated.

other changes introduce some invalidations in other nearby lines and its a little confusing as to what the marks exactly mean

**Comment by ArbitRandomUser** [comment]
also is there a way to disable this altogether ?
maybe the sign mark can be an config option and setting it to "" would disable the signs altogether

**Comment by Klafyvel** [comment]
It is supposed to track when an evaluated code block has been modified since evaluation. The thing is it uses the `[` and `]` marks, which are a bit tricky sometimes. It seems it broke between the time I implemented it and when I merded the PR. It should be fairly easy to add an configuration option to disable that.

**Comment by ArbitRandomUser** [comment]
do you remember a commit where it would have been working right ?

**Comment by Klafyvel** [comment]
For sure it worked when I wrote that comment: https://github.com/Klafyvel/nvim-smuggler/pull/15#issuecomment-2294793959 since there's a video, I believe it worked here as well: https://github.com/Klafyvel/nvim-smuggler/pull/15#issuecomment-2308865954 .

**Comment by Klafyvel** [comment]
If you want to debug that, I'd advise setting the log level to "debug", that way the evaluated chunks will have a clear unmistakable highlight (they get the `TermCursor` highlight group).

**Comment by ArbitRandomUser** [comment]
it seems the marks are updated only after a shift to normal mode from insert mode 

was just playing around with the following autocmd enabled
```
autocmd TextChangedI * :lua vim.print({"beg",vim.api.nvim_buf_get_mark(0,"["),"end",vim.api.nvim_buf_get_mark(0,"]")})
```

**Comment by ArbitRandomUser** [comment]
is it intended that chunk invalidation gets called at every keystroke

**Comment by Klafyvel** [comment]
Yes, it was intended. Wether this is wise is another question.

**Comment by ArbitRandomUser** [comment]
i'm having a little trouble wrapping my head around how its structured.

`invalidate_changed_chunks` is invoked only when `update_chunk_display_event` is set.

the event `buffer.update_chunk_display_event` is set only inside `delete_interesected_chunks` which is called only inside reslime functions .
i.e when either `Smuggle` or `SmuggleVisual` etc are called.

so how does it end up being called every keystroke ?

**Comment by ArbitRandomUser** [comment]
*every keystroke in insert mode

**Comment by ArbitRandomUser** [comment]
okay nvm it just occured to me to look for an autocmd when i was done typing this

**Comment by ArbitRandomUser** [comment]
okay not exactly a solution , but a compromise would be to have set the event at `InsertLeave`  over here ?

https://github.com/Klafyvel/nvim-smuggler/blob/43fb38603da9eb43c208bb79386b99827fca5f4f/lua/smuggler/ui.lua#L440-L443

**Comment by ArbitRandomUser** [comment]
okay i thought it worked but nope , that still does the wrong thing

**Comment by ArbitRandomUser** [comment]
okay here is something that works 

instead of finding entire chunks, if we treat every keystroke as a "single character chunk" find intersections and invalidate them.

https://github.com/Klafyvel/nvim-smuggler/pull/43
