### ISSUE TITLE
Add an option to set a fixed socket path.

### ISSUE THREAD

**Issue by Klafyvel** [Klafyvel/nvim-smuggler#8]
Following https://github.com/Klafyvel/REPLSmuggler.jl/issues/10, it would be interesting to have a configuration option that fixes the name of the julia socket used rather than asking it to the user. 

The most flexible way would be to allow the user to specify a lua function in the configuration, whose task would be to return a path to the socket. For example:
```lua
{
  "klafyvel/nvim-smuggler",
  opts = {
    socket_choice_function = function()
      local last_pane_id = trim(vim.fn.system('tmux display -pt "{last}" "#{pane_id}"'))
      return "~/juliasockets/" .. last_pane_id
    end
  },
  dependencies = { "nvim-neotest/nvim-nio" },
}
```

And then, with https://github.com/Klafyvel/REPLSmuggler.jl/pull/12, you could have in your `startup.jl` file something like (not tested):
```julia
atreplinit() do repl
  using REPLSmuggler
  io = IOBuffer()
  run(pipeline(`tmux display -p "#{pane_id}"`, io))
  name = filter(!isspace, String(take!(io)))
  smuggle(name, basepath="~/juliasockets")
end
```

What do you think @fredrikekre?

**Comment by fredrikekre** [comment]
Thanks for looking into this.

For me the extra configurability with a basepath isn't necessarily necessary, but specifying the socket name in `REPLSmuggle.smuggle()` would be great and then the same discovery mechanism that you have already now can be used on the neovim side.
